# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
default_events:
  - issues
  - issue_comment
  - label
  - pull_request
  - pull_request_review
  - pull_request_review_comment
  - repository

# The set of permissions needed by the GitHub App.
default_permissions:
  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

  # Issues and related comments, assignees, labels, and milestones.
  issues: write

  # Pull requests and related comments, assignees, labels, milestones, and merges.
  pull_requests: write

  # Search repositories, list collaborators, and access repository metadata.
  metadata: read

  # Manage the post-receive hooks for a repository.
  repository_hooks: read

# The name of the GitHub App. Defaults to the name specified in package.json
name: Aider Bot

# A description of the GitHub App.
description: A GitHub bot that uses Aider to automatically fix issues with specific labels

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
public: false
